# Generated by Django 5.2.4 on 2025-11-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='notificacio_usuario_ef49b7_idx',
            old_name='notificacio_usuario_2c9179_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='notificacio_fecha_c_24f290_idx',
            old_name='notificacio_fecha_c_83839e_idx',
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='notificaciones',
        ),
    ]
