# Generated by Django 5.2.4 on 2025-10-18 21:43

import apps.usuarios.validators
import django.core.validators
from django.db import migrations, models


def asignar_cedulas_default(apps, schema_editor):
    """Asigna cédulas temporales a usuarios que no tienen una"""
    Usuario = apps.get_model('usuarios', 'Usuario')
    usuarios_sin_cedula = Usuario.objects.filter(cedula__isnull=True)
    
    for idx, usuario in enumerate(usuarios_sin_cedula):
        # Asignar cédula temporal única
        usuario.cedula = f"999999{idx:04d}"[:10]
        usuario.save()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_cedula_usuario_correo_usuario_nombre_and_more'),
    ]

    operations = [
        # Primero asignar valores a los registros null
        migrations.RunPython(asignar_cedulas_default, reverse_code=migrations.RunPython.noop),
        # Luego aplicar la restricción NOT NULL
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(help_text='Cédula ecuatoriana de 10 dígitos', max_length=10, unique=True, validators=[apps.usuarios.validators.validar_cedula_ecuatoriana]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2, 'El nombre debe tener al menos 2 caracteres')]),
        ),
    ]
