# Generated by Django 5.2.4 on 2025-10-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_cedula_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('Quito', 'Quito'), ('Guayaquil', 'Guayaquil'), ('Cuenca', 'Cuenca'), ('Ambato', 'Ambato'), ('Manta', 'Manta'), ('Loja', 'Loja'), ('Esmeraldas', 'Esmeraldas'), ('Riobamba', 'Riobamba'), ('Machala', 'Machala'), ('Santo Domingo', 'Santo Domingo'), ('Ibarra', 'Ibarra'), ('Portoviejo', 'Portoviejo'), ('Durán', 'Durán'), ('Quevedo', 'Quevedo'), ('Milagro', 'Milagro')], help_text='Ciudad de residencia del usuario', max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada de latitud para ubicación en mapa', max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada de longitud para ubicación en mapa', max_digits=9, null=True, verbose_name='Longitud'),
        ),
    ]
