# Generated by Django 5.2.4 on 2025-10-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_ciudad_usuario_latitud_usuario_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='canton',
            field=models.CharField(blank=True, help_text='Cantón de residencia del usuario', max_length=100, null=True, verbose_name='Cantón'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='provincia',
            field=models.CharField(blank=True, help_text='Provincia de residencia del usuario', max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad de residencia del usuario', max_length=100, null=True, verbose_name='Ciudad'),
        ),
    ]
