# Generated by Django 5.2.4 on 2025-10-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_canton_usuario_provincia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cupo_anual',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Límite de peso anual que puede enviar el comprador', max_digits=10, verbose_name='Cupo Anual (kg)'),
        ),
    ]
