# Generated by Django 5.2.4 on 2025-11-25 03:10

from django.db import migrations


class Migration(migrations.Migration):
    """
    Migración para reflejar cambios ya aplicados manualmente en la BD:
    - Eliminación de columnas: first_name, last_name, email, is_active, latitud, longitud
    - Renombrado de tabla: usuarios_usuario -> usuarios
    """
    dependencies = [
        ('usuarios', '0006_usuario_cupo_anual'),
    ]

    operations = [
        # Renombrar tabla si existe con nombre por defecto
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    -- Si existe usuarios_usuario (nombre por defecto) pero no usuarios, renombrar
                    IF EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'usuarios_usuario'
                    ) AND NOT EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'usuarios'
                    ) THEN
                        ALTER TABLE usuarios_usuario RENAME TO usuarios;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'usuarios'
                    ) AND NOT EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'usuarios_usuario'
                    ) THEN
                        ALTER TABLE usuarios RENAME TO usuarios_usuario;
                    END IF;
                END $$;
            """
        ),
        # Eliminar columnas si existen
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios') THEN
                        -- Eliminar columnas solo si existen
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = 'usuarios' AND column_name = 'email'
                        ) THEN
                            ALTER TABLE usuarios DROP COLUMN email;
                        END IF;
                        
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = 'usuarios' AND column_name = 'first_name'
                        ) THEN
                            ALTER TABLE usuarios DROP COLUMN first_name;
                        END IF;
                        
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = 'usuarios' AND column_name = 'last_name'
                        ) THEN
                            ALTER TABLE usuarios DROP COLUMN last_name;
                        END IF;
                        
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = 'usuarios' AND column_name = 'latitud'
                        ) THEN
                            ALTER TABLE usuarios DROP COLUMN latitud;
                        END IF;
                        
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = 'usuarios' AND column_name = 'longitud'
                        ) THEN
                            ALTER TABLE usuarios DROP COLUMN longitud;
                        END IF;
                    END IF;
                END $$;
            """,
            reverse_sql="-- No se puede revertir automáticamente"
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='usuario',
                    name='email',
                ),
                migrations.RemoveField(
                    model_name='usuario',
                    name='first_name',
                ),
                migrations.RemoveField(
                    model_name='usuario',
                    name='is_active',
                ),
                migrations.RemoveField(
                    model_name='usuario',
                    name='last_name',
                ),
                migrations.RemoveField(
                    model_name='usuario',
                    name='latitud',
                ),
                migrations.RemoveField(
                    model_name='usuario',
                    name='longitud',
                ),
                migrations.AlterModelTable(
                    name='usuario',
                    table='usuarios',
                ),
            ]
        ),
    ]
