# Generated by Django 5.2.4 on 2025-11-25 03:10

from django.db import migrations


def renombrar_tabla(apps, schema_editor):
    """Renombra usuarios_usuario → usuarios si aplica."""
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios_usuario'
                )
            """)
            existe_vieja = cursor.fetchone()[0]
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios'
                )
            """)
            existe_nueva = cursor.fetchone()[0]
        elif vendor == 'sqlite':
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='usuarios_usuario'")
            existe_vieja = cursor.fetchone() is not None
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='usuarios'")
            existe_nueva = cursor.fetchone() is not None

    if existe_vieja and not existe_nueva:
        schema_editor.execute("ALTER TABLE usuarios_usuario RENAME TO usuarios;")
        # Renombrar tablas M2M heredadas de AbstractUser
        with schema_editor.connection.cursor() as cursor:
            if vendor == 'postgresql':
                cursor.execute("SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios_usuario_groups')")
                tiene_groups = cursor.fetchone()[0]
                cursor.execute("SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios_usuario_user_permissions')")
                tiene_perms = cursor.fetchone()[0]
            else:
                cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='usuarios_usuario_groups'")
                tiene_groups = cursor.fetchone() is not None
                cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='usuarios_usuario_user_permissions'")
                tiene_perms = cursor.fetchone() is not None
        if tiene_groups:
            schema_editor.execute("ALTER TABLE usuarios_usuario_groups RENAME TO usuarios_groups;")
        if tiene_perms:
            schema_editor.execute("ALTER TABLE usuarios_usuario_user_permissions RENAME TO usuarios_user_permissions;")


def revertir_renombrar_tabla(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            cursor.execute("SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios')")
            existe_nueva = cursor.fetchone()[0]
            cursor.execute("SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios_usuario')")
            existe_vieja = cursor.fetchone()[0]
        elif vendor == 'sqlite':
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='usuarios'")
            existe_nueva = cursor.fetchone() is not None
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='usuarios_usuario'")
            existe_vieja = cursor.fetchone() is not None

    if existe_nueva and not existe_vieja:
        schema_editor.execute("ALTER TABLE usuarios RENAME TO usuarios_usuario;")


def eliminar_columnas(apps, schema_editor):
    """Elimina columnas heredadas de AbstractUser si existen en la tabla usuarios."""
    columnas_a_eliminar = ['email', 'first_name', 'last_name', 'latitud', 'longitud']
    vendor = schema_editor.connection.vendor

    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            cursor.execute("""
                SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios')
            """)
            if not cursor.fetchone()[0]:
                return
            cursor.execute("""
                SELECT column_name FROM information_schema.columns WHERE table_name = 'usuarios'
            """)
            columnas_existentes = {row[0] for row in cursor.fetchall()}
        elif vendor == 'sqlite':
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='usuarios'")
            if cursor.fetchone() is None:
                return
            cursor.execute("PRAGMA table_info(usuarios)")
            columnas_existentes = {row[1] for row in cursor.fetchall()}

    for col in columnas_a_eliminar:
        if col in columnas_existentes:
            schema_editor.execute(f"ALTER TABLE usuarios DROP COLUMN {col};")


class Migration(migrations.Migration):
    """
    Migración para reflejar cambios ya aplicados manualmente en la BD:
    - Eliminación de columnas: first_name, last_name, email, is_active, latitud, longitud
    - Renombrado de tabla: usuarios_usuario -> usuarios
    """
    dependencies = [
        ('usuarios', '0006_usuario_cupo_anual'),
    ]

    operations = [
        migrations.RunPython(renombrar_tabla, revertir_renombrar_tabla),
        migrations.RunPython(eliminar_columnas, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(model_name='usuario', name='email'),
                migrations.RemoveField(model_name='usuario', name='first_name'),
                migrations.RemoveField(model_name='usuario', name='is_active'),
                migrations.RemoveField(model_name='usuario', name='last_name'),
                migrations.RemoveField(model_name='usuario', name='latitud'),
                migrations.RemoveField(model_name='usuario', name='longitud'),
                migrations.AlterModelTable(name='usuario', table='usuarios'),
            ]
        ),
    ]
