# Generated by Django 5.2.4 on 2025-11-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_eliminar_campos_abstractuser'),
    ]

    operations = [
        # Primero asegurar que la tabla se llame 'usuarios'
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    -- Si existe usuarios_usuario pero no usuarios, renombrar
                    IF EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'usuarios_usuario'
                    ) AND NOT EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'usuarios'
                    ) THEN
                        ALTER TABLE usuarios_usuario RENAME TO usuarios;
                        -- También renombrar tablas relacionadas
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios_usuario_groups') THEN
                            ALTER TABLE usuarios_usuario_groups RENAME TO usuarios_groups;
                        END IF;
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios_usuario_user_permissions') THEN
                            ALTER TABLE usuarios_usuario_user_permissions RENAME TO usuarios_user_permissions;
                        END IF;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios') THEN
                        ALTER TABLE usuarios RENAME TO usuarios_usuario;
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios_groups') THEN
                            ALTER TABLE usuarios_groups RENAME TO usuarios_usuario_groups;
                        END IF;
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios_user_permissions') THEN
                            ALTER TABLE usuarios_user_permissions RENAME TO usuarios_usuario_user_permissions;
                        END IF;
                    END IF;
                END $$;
            """
        ),
        # Ahora modificar el campo
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    -- Verificar si la tabla existe (ya renombrada a 'usuarios' o todavía 'usuarios_usuario')
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios') THEN
                        -- Si el campo es_activo existe y no tiene db_column, agregarlo
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = 'usuarios' 
                            AND column_name = 'es_activo'
                            AND table_schema = 'public'
                        ) THEN
                            -- El campo ya existe, solo verificar que tenga el db_column correcto
                            -- Si is_active existe, es_activo debe mapear a is_active
                            IF EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'usuarios' 
                                AND column_name = 'is_active'
                            ) THEN
                                -- Ya existe is_active, es_activo debe mapear a is_active (ya está configurado)
                                NULL; -- No hacer nada
                            ELSE
                                -- Renombrar es_activo a is_active si no existe is_active
                                ALTER TABLE usuarios RENAME COLUMN es_activo TO is_active;
                            END IF;
                        ELSIF EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = 'usuarios' 
                            AND column_name = 'is_active'
                        ) THEN
                            -- is_active ya existe, no hacer nada
                            NULL;
                        ELSE
                            -- Crear el campo is_active
                            ALTER TABLE usuarios ADD COLUMN is_active BOOLEAN DEFAULT TRUE NOT NULL;
                        END IF;
                    ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios_usuario') THEN
                        -- Mismo proceso pero con usuarios_usuario
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = 'usuarios_usuario' 
                            AND column_name = 'es_activo'
                        ) THEN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns 
                                WHERE table_name = 'usuarios_usuario' 
                                AND column_name = 'is_active'
                            ) THEN
                                ALTER TABLE usuarios_usuario RENAME COLUMN es_activo TO is_active;
                            END IF;
                        ELSIF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = 'usuarios_usuario' 
                            AND column_name = 'is_active'
                        ) THEN
                            ALTER TABLE usuarios_usuario ADD COLUMN is_active BOOLEAN DEFAULT TRUE NOT NULL;
                        END IF;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'usuarios') THEN
                        IF EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = 'usuarios' AND column_name = 'is_active'
                        ) AND NOT EXISTS (
                            SELECT 1 FROM information_schema.columns 
                            WHERE table_name = 'usuarios' AND column_name = 'es_activo'
                        ) THEN
                            ALTER TABLE usuarios RENAME COLUMN is_active TO es_activo;
                        END IF;
                    END IF;
                END $$;
            """
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='usuario',
                    name='es_activo',
                    field=models.BooleanField(db_column='is_active', default=True),
                ),
            ]
        ),
    ]
