# Generated by Django 5.2.4 on 2025-11-26 20:46

from django.db import migrations, models


def _get_columns(cursor, vendor, table):
    if vendor == 'postgresql':
        cursor.execute(
            "SELECT column_name FROM information_schema.columns WHERE table_name = %s",
            [table]
        )
    else:
        cursor.execute(f"PRAGMA table_info({table})")
    return {row[0] if vendor == 'postgresql' else row[1] for row in cursor.fetchall()}


def _table_exists(cursor, vendor, table):
    if vendor == 'postgresql':
        cursor.execute(
            "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = %s)",
            [table]
        )
        return cursor.fetchone()[0]
    else:
        cursor.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name=?", [table]
        )
        return cursor.fetchone() is not None


def renombrar_tabla(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        existe_vieja = _table_exists(cursor, vendor, 'usuarios_usuario')
        existe_nueva = _table_exists(cursor, vendor, 'usuarios')
    if existe_vieja and not existe_nueva:
        schema_editor.execute("ALTER TABLE usuarios_usuario RENAME TO usuarios;")
        with schema_editor.connection.cursor() as cursor:
            if _table_exists(cursor, vendor, 'usuarios_usuario_groups'):
                schema_editor.execute("ALTER TABLE usuarios_usuario_groups RENAME TO usuarios_groups;")
            if _table_exists(cursor, vendor, 'usuarios_usuario_user_permissions'):
                schema_editor.execute(
                    "ALTER TABLE usuarios_usuario_user_permissions RENAME TO usuarios_user_permissions;"
                )


def revertir_renombrar_tabla(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        existe_nueva = _table_exists(cursor, vendor, 'usuarios')
        existe_vieja = _table_exists(cursor, vendor, 'usuarios_usuario')
    if existe_nueva and not existe_vieja:
        schema_editor.execute("ALTER TABLE usuarios RENAME TO usuarios_usuario;")
        with schema_editor.connection.cursor() as cursor:
            if _table_exists(cursor, vendor, 'usuarios_groups'):
                schema_editor.execute("ALTER TABLE usuarios_groups RENAME TO usuarios_usuario_groups;")
            if _table_exists(cursor, vendor, 'usuarios_user_permissions'):
                schema_editor.execute(
                    "ALTER TABLE usuarios_user_permissions RENAME TO usuarios_usuario_user_permissions;"
                )


def ajustar_campo_is_active(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    for tabla in ('usuarios', 'usuarios_usuario'):
        with schema_editor.connection.cursor() as cursor:
            if not _table_exists(cursor, vendor, tabla):
                continue
            cols = _get_columns(cursor, vendor, tabla)

        tiene_es_activo = 'es_activo' in cols
        tiene_is_active = 'is_active' in cols

        if tiene_es_activo and tiene_is_active:
            schema_editor.execute(f"ALTER TABLE {tabla} DROP COLUMN es_activo;")
        elif tiene_es_activo and not tiene_is_active:
            schema_editor.execute(f"ALTER TABLE {tabla} RENAME COLUMN es_activo TO is_active;")
        elif not tiene_es_activo and not tiene_is_active:
            schema_editor.execute(
                f"ALTER TABLE {tabla} ADD COLUMN is_active BOOLEAN DEFAULT TRUE NOT NULL;"
            )
        break  # solo procesar la primera tabla que exista


def revertir_is_active(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if not _table_exists(cursor, vendor, 'usuarios'):
            return
        cols = _get_columns(cursor, vendor, 'usuarios')
    if 'is_active' in cols and 'es_activo' not in cols:
        schema_editor.execute("ALTER TABLE usuarios RENAME COLUMN is_active TO es_activo;")


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_eliminar_campos_abstractuser'),
    ]

    operations = [
        migrations.RunPython(renombrar_tabla, revertir_renombrar_tabla),
        migrations.RunPython(ajustar_campo_is_active, revertir_is_active),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='usuario',
                    name='es_activo',
                    field=models.BooleanField(db_column='is_active', default=True),
                ),
            ]
        ),
    ]
