# Generated by Django 5.2.4 on 2026-01-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_usuario_es_activo_usuario_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
