# Generated by Django 5.2.4 on 2025-10-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0003_remove_archivo_categoria_remove_archivo_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='costo_servicio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo calculado automáticamente según tarifas', max_digits=12, verbose_name='Costo del Servicio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo calculado según tarifa de categoría y peso', max_digits=10, verbose_name='Costo de Envío'),
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('electronica', 'Electrónica'), ('ropa', 'Ropa'), ('hogar', 'Hogar'), ('deportes', 'Deportes'), ('otros', 'Otros')], max_length=50, verbose_name='Categoría')),
                ('peso_minimo', models.DecimalField(decimal_places=2, help_text='Peso mínimo en kilogramos para aplicar esta tarifa', max_digits=8, verbose_name='Peso Mínimo (kg)')),
                ('peso_maximo', models.DecimalField(decimal_places=2, help_text='Peso máximo en kilogramos para aplicar esta tarifa', max_digits=8, verbose_name='Peso Máximo (kg)')),
                ('precio_por_kg', models.DecimalField(decimal_places=2, help_text='Precio en dólares por kilogramo', max_digits=8, verbose_name='Precio por Kg ($)')),
                ('cargo_base', models.DecimalField(decimal_places=2, default=0, help_text='Cargo fijo base para esta categoría y rango de peso', max_digits=8, verbose_name='Cargo Base ($)')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'ordering': ['categoria', 'peso_minimo'],
                'unique_together': {('categoria', 'peso_minimo', 'peso_maximo')},
            },
        ),
    ]
