# Generated by Django 5.2.4 on 2025-10-20 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0004_envio_costo_servicio_producto_costo_envio_tarifa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='importaciones/%Y/%m/', verbose_name='Archivo Excel')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre Original del Archivo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validando', 'Validando'), ('validado', 'Validado'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('total_registros', models.IntegerField(default=0, verbose_name='Total de Registros')),
                ('registros_validos', models.IntegerField(default=0, verbose_name='Registros Válidos')),
                ('registros_errores', models.IntegerField(default=0, verbose_name='Registros con Errores')),
                ('registros_duplicados', models.IntegerField(default=0, verbose_name='Registros Duplicados')),
                ('registros_procesados', models.IntegerField(default=0, verbose_name='Registros Procesados')),
                ('errores_validacion', models.JSONField(blank=True, default=dict, help_text='Detalles de errores encontrados durante la validación', verbose_name='Errores de Validación')),
                ('columnas_mapeadas', models.JSONField(blank=True, default=dict, help_text='Mapeo entre columnas del Excel y campos del modelo', verbose_name='Mapeo de Columnas')),
                ('registros_seleccionados', models.JSONField(blank=True, default=list, help_text='Lista de índices de registros que se importarán', verbose_name='Índices de Registros Seleccionados')),
                ('mensaje_resultado', models.TextField(blank=True, null=True, verbose_name='Mensaje de Resultado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Importación de Excel',
                'verbose_name_plural': 'Importaciones de Excel',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
