# Generated by Django 5.2.4 on 2025-11-22 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0005_importacionexcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión'),
        ),
    ]
