# Generated by Django 5.2.4 on 2025-11-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0006_alter_envio_fecha_emision'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='envio',
            table='envio',
        ),
        migrations.AlterModelTable(
            name='importacionexcel',
            table='archivo',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
        migrations.AlterModelTable(
            name='tarifa',
            table='tarifa',
        ),
    ]
