# Generated by Django 5.2.4 on 2026-01-03 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0007_alter_envio_table_alter_importacionexcel_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='envio',
            index=models.Index(fields=['hawb'], name='envio_hawb_27ed0a_idx'),
        ),
        migrations.AddIndex(
            model_name='envio',
            index=models.Index(fields=['comprador', 'fecha_emision'], name='envio_comprad_de0b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='envio',
            index=models.Index(fields=['estado', 'fecha_emision'], name='envio_estado_1d5818_idx'),
        ),
        migrations.AddIndex(
            model_name='envio',
            index=models.Index(fields=['-fecha_emision'], name='envio_fecha_e_33b2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['envio', 'categoria'], name='producto_envio_i_39515c_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='producto_categor_7f5242_idx'),
        ),
    ]
