# Generated by Django 5.2.4 on 2026-01-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0008_envio_envio_hawb_27ed0a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='cantidad_total',
            field=models.IntegerField(default=0, verbose_name='Cantidad Total'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='peso_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Peso Total'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total'),
        ),
    ]
