# Generated by Django 5.2.4 on 2026-01-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0010_remove_envio_costo_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='costo_servicio',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Costo calculado automáticamente según tarifas', max_digits=12, verbose_name='Costo del Servicio'),
        ),
    ]
