# Generated by Django 5.2.4 on 2026-01-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0011_aumentar_decimales_costo_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor'),
        ),
    ]
