# Generated by Django 5.2.4 on 2026-01-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0012_aumentar_decimales_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='peso_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Peso Total'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='valor_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Valor Total'),
        ),
    ]
