# Generated by Django 5.2.4 on 2026-03-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0013_aumentar_decimales_envio_totales'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
