# Generated by Django 5.2.4 on 2025-12-31 16:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archivos', '0007_alter_envio_table_alter_importacionexcel_table_and_more'),
        ('busqueda', '0010_rename_embedding_b_usuario_idx_embedding_b_usuario_275ca3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la prueba de carga', max_length=200, verbose_name='Nombre de la Prueba')),
                ('tipo_prueba', models.CharField(choices=[('busqueda_semantica', 'Búsqueda Semántica'), ('registro_envio', 'Registro de Envío')], max_length=50, verbose_name='Tipo de Prueba')),
                ('nivel_carga', models.PositiveIntegerField(help_text='Cantidad de operaciones a ejecutar (1, 10, 30)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nivel de Carga')),
                ('tipo_registro', models.CharField(blank=True, choices=[('manual', 'Manual (simulado)'), ('automatico', 'Automático')], help_text='Solo aplica para pruebas de registro de envío', max_length=50, null=True, verbose_name='Tipo de Registro')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('tiempo_promedio_ms', models.FloatField(default=0.0, verbose_name='Tiempo Promedio (ms)')),
                ('tiempo_minimo_ms', models.IntegerField(default=0, verbose_name='Tiempo Mínimo (ms)')),
                ('tiempo_maximo_ms', models.IntegerField(default=0, verbose_name='Tiempo Máximo (ms)')),
                ('cpu_promedio', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='CPU Promedio (%)')),
                ('cpu_maximo', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='CPU Máximo (%)')),
                ('ram_promedio_mb', models.FloatField(default=0.0, verbose_name='RAM Promedio (MB)')),
                ('ram_maximo_mb', models.FloatField(default=0.0, verbose_name='RAM Máximo (MB)')),
                ('total_exitosos', models.PositiveIntegerField(default=0)),
                ('total_errores', models.PositiveIntegerField(default=0)),
                ('datos_prueba', models.JSONField(blank=True, help_text='Consultas o datos utilizados en la prueba', null=True, verbose_name='Datos de Prueba')),
                ('ejecutado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_carga_ejecutadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prueba de Carga',
                'verbose_name_plural': 'Pruebas de Carga',
                'db_table': 'prueba_carga',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='MetricaRendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso', models.CharField(choices=[('registro_envio_manual', 'Registro de Envío Manual'), ('registro_envio_automatico', 'Registro de Envío Automático'), ('busqueda_semantica', 'Búsqueda Semántica')], max_length=50, verbose_name='Proceso')),
                ('tiempo_respuesta_ms', models.IntegerField(default=0, verbose_name='Tiempo de Respuesta (ms)')),
                ('uso_cpu', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Uso de CPU (%)')),
                ('uso_ram_mb', models.FloatField(default=0.0, verbose_name='Uso de RAM (MB)')),
                ('fecha_medicion', models.DateTimeField(auto_now_add=True)),
                ('nivel_carga', models.PositiveIntegerField(blank=True, help_text='Cantidad de operaciones simultáneas (1, 10, 30)', null=True, verbose_name='Nivel de Carga')),
                ('exito', models.BooleanField(default=True, help_text='Indica si la operación fue exitosa', verbose_name='Éxito')),
                ('detalles', models.JSONField(blank=True, help_text='Información adicional sobre la operación', null=True, verbose_name='Detalles Adicionales')),
                ('prueba_carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metricas_individuales', to='metricas.pruebacarga', verbose_name='Prueba de Carga')),
            ],
            options={
                'verbose_name': 'Métrica de Rendimiento',
                'verbose_name_plural': 'Métricas de Rendimiento',
                'db_table': 'metrica_rendimiento',
                'ordering': ['-fecha_medicion'],
            },
        ),
        migrations.CreateModel(
            name='PruebaControladaSemantica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la prueba controlada', max_length=200, verbose_name='Nombre de la Prueba')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la prueba', null=True, verbose_name='Descripción')),
                ('consulta', models.TextField(help_text='Texto de la consulta a evaluar', verbose_name='Consulta de Prueba')),
                ('resultados_relevantes', models.JSONField(help_text='Lista de IDs de envíos que son relevantes para esta consulta', verbose_name='Resultados Relevantes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_semanticas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prueba Controlada Semántica',
                'verbose_name_plural': 'Pruebas Controladas Semánticas',
                'db_table': 'prueba_controlada_semantica',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MetricaSemantica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.TextField(verbose_name='Consulta')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('resultados_rankeados', models.JSONField(help_text='Lista de resultados con scores y posiciones', verbose_name='Resultados Rankeados')),
                ('mrr', models.FloatField(blank=True, help_text='MRR calculado sobre los resultados', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='MRR (Mean Reciprocal Rank)')),
                ('ndcg_10', models.FloatField(blank=True, help_text='Normalized Discounted Cumulative Gain@10', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='nDCG@10')),
                ('precision_5', models.FloatField(blank=True, help_text='Precisión en los primeros 5 resultados', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Precision@5')),
                ('total_resultados', models.PositiveIntegerField(default=0)),
                ('total_relevantes_encontrados', models.PositiveIntegerField(default=0)),
                ('tiempo_procesamiento_ms', models.IntegerField(default=0, verbose_name='Tiempo de Procesamiento (ms)')),
                ('logs_pipeline', models.JSONField(blank=True, help_text='Logs detallados de cada etapa del proceso semántico', null=True, verbose_name='Logs del Pipeline')),
                ('modelo_embedding', models.CharField(default='text-embedding-3-small', max_length=100, verbose_name='Modelo de Embedding Utilizado')),
                ('metrica_ordenamiento', models.CharField(default='score_combinado', max_length=50, verbose_name='Métrica de Ordenamiento')),
                ('busqueda_semantica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='busqueda.embeddingbusqueda', verbose_name='Búsqueda Semántica')),
                ('prueba_controlada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='metricas.pruebacontroladasemantica', verbose_name='Prueba Controlada')),
            ],
            options={
                'verbose_name': 'Métrica Semántica',
                'verbose_name_plural': 'Métricas Semánticas',
                'db_table': 'metrica_semantica',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroGeneracionEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('generado', 'Generado Exitosamente'), ('error', 'Error en Generación'), ('omitido', 'Omitido (ya existía)')], default='generado', max_length=20, verbose_name='Estado')),
                ('dimension_embedding', models.PositiveIntegerField(default=1536, verbose_name='Dimensión del Embedding')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('tiempo_generacion_ms', models.IntegerField(default=0, verbose_name='Tiempo de Generación (ms)')),
                ('modelo_usado', models.CharField(default='text-embedding-3-small', max_length=100, verbose_name='Modelo Utilizado')),
                ('mensaje_error', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('tipo_proceso', models.CharField(choices=[('automatico', 'Automático (creación de envío)'), ('manual', 'Manual (comando de gestión)'), ('masivo', 'Masivo (importación)')], default='automatico', max_length=50, verbose_name='Tipo de Proceso')),
                ('embedding', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registro_generacion', to='busqueda.envioembedding', verbose_name='Embedding Generado')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_embedding', to='archivos.envio', verbose_name='Envío')),
            ],
            options={
                'verbose_name': 'Registro de Generación de Embedding',
                'verbose_name_plural': 'Registros de Generación de Embeddings',
                'db_table': 'registro_generacion_embedding',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroManualEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hawb', models.CharField(help_text='Número de envío simulado', max_length=50, verbose_name='HAWB')),
                ('tiempo_registro_segundos', models.FloatField(default=0.0, help_text='Tiempo medido con cronómetro para registro manual', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Tiempo de Registro (segundos)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('datos_envio', models.JSONField(blank=True, help_text='Datos del envío que se registró manualmente', null=True, verbose_name='Datos del Envío')),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre el registro manual', null=True, verbose_name='Notas')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_manuales_envios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Manual de Envío',
                'verbose_name_plural': 'Registros Manuales de Envíos',
                'db_table': 'registro_manual_envio',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='pruebacarga',
            index=models.Index(fields=['-fecha_ejecucion'], name='prueba_carg_fecha_e_9ba89e_idx'),
        ),
        migrations.AddIndex(
            model_name='pruebacarga',
            index=models.Index(fields=['tipo_prueba', 'nivel_carga'], name='prueba_carg_tipo_pr_93833d_idx'),
        ),
        migrations.AddIndex(
            model_name='metricarendimiento',
            index=models.Index(fields=['-fecha_medicion'], name='metrica_ren_fecha_m_6cb2df_idx'),
        ),
        migrations.AddIndex(
            model_name='metricarendimiento',
            index=models.Index(fields=['proceso', 'nivel_carga'], name='metrica_ren_proceso_aa79a2_idx'),
        ),
        migrations.AddIndex(
            model_name='metricarendimiento',
            index=models.Index(fields=['exito'], name='metrica_ren_exito_05009f_idx'),
        ),
        migrations.AddIndex(
            model_name='metricasemantica',
            index=models.Index(fields=['-fecha_calculo'], name='metrica_sem_fecha_c_90227c_idx'),
        ),
        migrations.AddIndex(
            model_name='metricasemantica',
            index=models.Index(fields=['mrr'], name='metrica_sem_mrr_175eed_idx'),
        ),
        migrations.AddIndex(
            model_name='metricasemantica',
            index=models.Index(fields=['ndcg_10'], name='metrica_sem_ndcg_10_048d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='metricasemantica',
            index=models.Index(fields=['precision_5'], name='metrica_sem_precisi_a65f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='registrogeneracionembedding',
            index=models.Index(fields=['-fecha_generacion'], name='registro_ge_fecha_g_887e08_idx'),
        ),
        migrations.AddIndex(
            model_name='registrogeneracionembedding',
            index=models.Index(fields=['estado'], name='registro_ge_estado_d22808_idx'),
        ),
        migrations.AddIndex(
            model_name='registrogeneracionembedding',
            index=models.Index(fields=['tipo_proceso'], name='registro_ge_tipo_pr_521c07_idx'),
        ),
        migrations.AddIndex(
            model_name='registrogeneracionembedding',
            index=models.Index(fields=['envio', '-fecha_generacion'], name='registro_ge_envio_i_451296_idx'),
        ),
        migrations.AddIndex(
            model_name='registromanualenvio',
            index=models.Index(fields=['-fecha_registro'], name='registro_ma_fecha_r_227a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='registromanualenvio',
            index=models.Index(fields=['registrado_por'], name='registro_ma_registr_fa2d98_idx'),
        ),
    ]
