# Generated by Django 5.2.4 on 2026-01-05 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaRendimientoCompleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ejecución')),
                ('resultados_json', models.JSONField(help_text='Resultados completos de la prueba en formato JSON', verbose_name='Resultados Completos')),
                ('tiempo_respuesta_manual_promedio', models.FloatField(blank=True, null=True, verbose_name='Tiempo Manual Promedio (s)')),
                ('tiempo_respuesta_web_promedio', models.FloatField(blank=True, null=True, verbose_name='Tiempo Web Promedio (s)')),
                ('mejora_factor', models.FloatField(blank=True, null=True, verbose_name='Factor de Mejora')),
                ('completada', models.BooleanField(default=True, verbose_name='Completada')),
                ('errores', models.TextField(blank=True, null=True, verbose_name='Errores Encontrados')),
                ('salida_completa', models.TextField(blank=True, help_text='Salida completa del comando para referencia', null=True, verbose_name='Salida Completa')),
                ('usuario_ejecutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pruebas_rendimiento_ejecutadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Ejecutor')),
            ],
            options={
                'verbose_name': 'Prueba de Rendimiento Completa',
                'verbose_name_plural': 'Pruebas de Rendimiento Completas',
                'db_table': 'prueba_rendimiento_completa',
                'ordering': ['-fecha_ejecucion'],
                'indexes': [models.Index(fields=['-fecha_ejecucion'], name='prueba_rend_fecha_e_ed5bcd_idx'), models.Index(fields=['usuario_ejecutor'], name='prueba_rend_usuario_2aa306_idx'), models.Index(fields=['completada'], name='prueba_rend_complet_9035a3_idx')],
            },
        ),
    ]
