# Generated by Django 5.2.4 on 2026-01-16 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0002_pruebarendimientocompleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProcesoRendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proceso', models.CharField(choices=[('M1', 'M1 - Ingresar usuario'), ('M2', 'M2 - Registrar nuevo usuario'), ('M3', 'M3 - Restablecer contraseña'), ('M4', 'M4 - Crear nuevo usuario'), ('M5', 'M5 - Listar usuarios'), ('M6', 'M6 - Modificar perfil'), ('M7', 'M7 - Crear nuevo envío'), ('M8', 'M8 - Modificar envío'), ('M9', 'M9 - Crear producto'), ('M10', 'M10 - Crear tarifa'), ('M11', 'M11 - Importar envíos'), ('M12', 'M12 - Exportar envíos'), ('M13', 'M13 - Buscar envíos'), ('M14', 'M14 - Buscar semánticamente')], max_length=10, verbose_name='Código del Proceso')),
                ('nombre_proceso', models.CharField(max_length=200, verbose_name='Nombre del Proceso')),
                ('tiempo_media', models.FloatField(verbose_name='Tiempo Media (s)')),
                ('tiempo_minimo', models.FloatField(verbose_name='Tiempo Mínimo (s)')),
                ('tiempo_maximo', models.FloatField(verbose_name='Tiempo Máximo (s)')),
                ('tiempo_mediana', models.FloatField(verbose_name='Tiempo Mediana (s)')),
                ('tiempo_desviacion', models.FloatField(verbose_name='Tiempo Desv. Est. (s)')),
                ('cpu_media', models.FloatField(verbose_name='CPU Media (%)')),
                ('cpu_minimo', models.FloatField(verbose_name='CPU Mínimo (%)')),
                ('cpu_maximo', models.FloatField(verbose_name='CPU Máximo (%)')),
                ('cpu_mediana', models.FloatField(verbose_name='CPU Mediana (%)')),
                ('cpu_desviacion', models.FloatField(verbose_name='CPU Desv. Est. (%)')),
                ('ram_media', models.FloatField(verbose_name='RAM Media (MB)')),
                ('ram_minimo', models.FloatField(verbose_name='RAM Mínimo (MB)')),
                ('ram_maximo', models.FloatField(verbose_name='RAM Máximo (MB)')),
                ('ram_mediana', models.FloatField(verbose_name='RAM Mediana (MB)')),
                ('ram_desviacion', models.FloatField(verbose_name='RAM Desv. Est. (MB)')),
                ('categoria_tiempo', models.CharField(choices=[('Excelente', 'Excelente (0-1s)'), ('Aceptable', 'Aceptable (1-3s)'), ('Deficiente', 'Deficiente (3-10s)'), ('Inaceptable', 'Inaceptable (>10s)')], max_length=20, verbose_name='Categoría Tiempo')),
                ('calificacion_tiempo', models.IntegerField(verbose_name='Calificación Tiempo (0-100)')),
                ('categoria_cpu', models.CharField(choices=[('Excelente', 'Excelente (0-0.5%)'), ('Muy bueno', 'Muy bueno (0.6-1.5%)'), ('Bueno', 'Bueno (1.6-2.5%)'), ('Aceptable', 'Aceptable (2.6-3.5%)'), ('Regular', 'Regular (3.6-4.5%)'), ('Malo', 'Malo (>4.6%)')], max_length=20, verbose_name='Categoría CPU')),
                ('calificacion_cpu', models.IntegerField(verbose_name='Calificación CPU (0-100)')),
                ('categoria_ram', models.CharField(choices=[('Excelente', 'Excelente (0-150 MB)'), ('Muy bueno', 'Muy bueno (151-250 MB)'), ('Bueno', 'Bueno (251-350 MB)'), ('Aceptable', 'Aceptable (351-450 MB)'), ('Regular', 'Regular (451-550 MB)'), ('Malo', 'Malo (>551 MB)')], max_length=20, verbose_name='Categoría RAM')),
                ('calificacion_ram', models.IntegerField(verbose_name='Calificación RAM (0-100)')),
                ('iteraciones_completadas', models.IntegerField(verbose_name='Iteraciones Completadas')),
                ('iteraciones_totales', models.IntegerField(verbose_name='Iteraciones Totales')),
                ('total_errores', models.IntegerField(default=0, verbose_name='Total de Errores')),
                ('tiempos_raw', models.JSONField(blank=True, help_text='Array con todos los tiempos medidos', null=True, verbose_name='Tiempos Raw')),
                ('cpus_raw', models.JSONField(blank=True, help_text='Array con todos los valores de CPU medidos', null=True, verbose_name='CPUs Raw')),
                ('rams_raw', models.JSONField(blank=True, help_text='Array con todos los valores de RAM medidos', null=True, verbose_name='RAMs Raw')),
                ('errores_detalle', models.JSONField(blank=True, help_text='Lista de errores encontrados durante la ejecución', null=True, verbose_name='Errores Detalle')),
                ('fecha_medicion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Medición')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_procesos', to='metricas.pruebarendimientocompleta', verbose_name='Prueba de Rendimiento')),
            ],
            options={
                'verbose_name': 'Detalle de Proceso de Rendimiento',
                'verbose_name_plural': 'Detalles de Procesos de Rendimiento',
                'db_table': 'detalle_proceso_rendimiento',
                'ordering': ['prueba', 'codigo_proceso'],
                'indexes': [models.Index(fields=['prueba', 'codigo_proceso'], name='detalle_pro_prueba__728b94_idx'), models.Index(fields=['codigo_proceso', '-fecha_medicion'], name='detalle_pro_codigo__47825e_idx'), models.Index(fields=['categoria_tiempo'], name='detalle_pro_categor_08816c_idx'), models.Index(fields=['categoria_cpu'], name='detalle_pro_categor_ed7bf6_idx'), models.Index(fields=['categoria_ram'], name='detalle_pro_categor_8e28d6_idx')],
            },
        ),
    ]
