# Generated by Django 5.2.4 on 2026-01-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metricas', '0003_detalleprocesorendimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprocesorendimiento',
            name='ram_desviacion',
            field=models.FloatField(verbose_name='RAM Desv. Est. (KB)'),
        ),
        migrations.AlterField(
            model_name='detalleprocesorendimiento',
            name='ram_maximo',
            field=models.FloatField(verbose_name='RAM Máximo (KB)'),
        ),
        migrations.AlterField(
            model_name='detalleprocesorendimiento',
            name='ram_media',
            field=models.FloatField(verbose_name='RAM Media (KB)'),
        ),
        migrations.AlterField(
            model_name='detalleprocesorendimiento',
            name='ram_mediana',
            field=models.FloatField(verbose_name='RAM Mediana (KB)'),
        ),
        migrations.AlterField(
            model_name='detalleprocesorendimiento',
            name='ram_minimo',
            field=models.FloatField(verbose_name='RAM Mínimo (KB)'),
        ),
    ]
