# Generated by Django 5.2.4 on 2025-07-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino_busqueda', models.CharField(max_length=255)),
                ('tipo_busqueda', models.CharField(default='general', max_length=50)),
                ('fecha_busqueda', models.DateTimeField(auto_now_add=True)),
                ('resultados_encontrados', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Historial de Búsqueda',
                'verbose_name_plural': 'Historial de Búsquedas',
                'ordering': ['-fecha_busqueda'],
            },
        ),
    ]
