# Generated by Django 5.2.4 on 2025-10-19 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0004_envio_costo_servicio_producto_costo_envio_tarifa'),
        ('busqueda', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaSemantica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200, verbose_name='Texto de Sugerencia')),
                ('categoria', models.CharField(choices=[('estado', 'Estado'), ('ciudad', 'Ciudad'), ('fecha', 'Fecha'), ('comprador', 'Comprador'), ('general', 'General')], default='general', max_length=50)),
                ('icono', models.CharField(default='fa-search', help_text='Clase de icono FontAwesome', max_length=50)),
                ('orden', models.IntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sugerencia Semántica',
                'verbose_name_plural': 'Sugerencias Semánticas',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='BusquedaSemantica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.TextField(verbose_name='Consulta')),
                ('resultados_encontrados', models.PositiveIntegerField(default=0)),
                ('tiempo_respuesta', models.IntegerField(default=0, help_text='Tiempo de respuesta en milisegundos')),
                ('fecha_busqueda', models.DateTimeField(auto_now_add=True)),
                ('filtros_aplicados', models.JSONField(blank=True, null=True, verbose_name='Filtros Aplicados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Búsqueda Semántica',
                'verbose_name_plural': 'Búsquedas Semánticas',
                'ordering': ['-fecha_busqueda'],
            },
        ),
        migrations.CreateModel(
            name='EnvioEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.TextField(help_text='Vector de embedding serializado como JSON', verbose_name='Vector de Embedding')),
                ('texto_indexado', models.TextField(help_text='Texto que fue usado para generar el embedding', verbose_name='Texto Indexado')),
                ('fecha_generacion', models.DateTimeField(auto_now=True)),
                ('modelo_usado', models.CharField(default='text-embedding-3-small', max_length=100)),
                ('envio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='archivos.envio', verbose_name='Envío')),
            ],
            options={
                'verbose_name': 'Embedding de Envío',
                'verbose_name_plural': 'Embeddings de Envíos',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSemantico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_relevante', models.BooleanField(help_text='Indica si el usuario consideró relevante este resultado', verbose_name='Es Relevante')),
                ('puntuacion_similitud', models.FloatField(help_text='Puntuación de similitud original del resultado', verbose_name='Puntuación de Similitud')),
                ('fecha_feedback', models.DateTimeField(auto_now_add=True)),
                ('busqueda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='busqueda.busquedasemantica')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivos.envio', verbose_name='Envío')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Semántico',
                'verbose_name_plural': 'Feedbacks Semánticos',
                'ordering': ['-fecha_feedback'],
                'unique_together': {('usuario', 'envio', 'busqueda')},
            },
        ),
    ]
