# Generated by Django 5.2.4 on 2025-10-19 22:30

from django.db import migrations


def cargar_sugerencias_iniciales(apps, schema_editor):
    """Carga sugerencias semánticas predefinidas"""
    SugerenciaSemantica = apps.get_model('busqueda', 'SugerenciaSemantica')
    
    sugerencias = [
        {
            'texto': 'envíos entregados esta semana',
            'categoria': 'fecha',
            'icono': 'fa-calendar-check',
            'orden': 1
        },
        {
            'texto': 'paquetes pendientes de entrega',
            'categoria': 'estado',
            'icono': 'fa-clock',
            'orden': 2
        },
        {
            'texto': 'envíos a Quito',
            'categoria': 'ciudad',
            'icono': 'fa-map-marker-alt',
            'orden': 3
        },
        {
            'texto': 'envíos a Guayaquil',
            'categoria': 'ciudad',
            'icono': 'fa-map-marker-alt',
            'orden': 4
        },
        {
            'texto': 'envíos en tránsito',
            'categoria': 'estado',
            'icono': 'fa-truck',
            'orden': 5
        },
        {
            'texto': 'paquetes del último mes',
            'categoria': 'fecha',
            'icono': 'fa-calendar-alt',
            'orden': 6
        },
        {
            'texto': 'envíos cancelados',
            'categoria': 'estado',
            'icono': 'fa-times-circle',
            'orden': 7
        },
        {
            'texto': 'envíos a Cuenca',
            'categoria': 'ciudad',
            'icono': 'fa-map-marker-alt',
            'orden': 8
        },
        {
            'texto': 'paquetes de electrónica',
            'categoria': 'general',
            'icono': 'fa-laptop',
            'orden': 9
        },
        {
            'texto': 'envíos de mayor valor',
            'categoria': 'general',
            'icono': 'fa-dollar-sign',
            'orden': 10
        },
    ]
    
    for sugerencia_data in sugerencias:
        SugerenciaSemantica.objects.get_or_create(
            texto=sugerencia_data['texto'],
            defaults={
                'categoria': sugerencia_data['categoria'],
                'icono': sugerencia_data['icono'],
                'orden': sugerencia_data['orden'],
                'activa': True
            }
        )


def eliminar_sugerencias(apps, schema_editor):
    """Elimina las sugerencias cargadas (para reversa)"""
    SugerenciaSemantica = apps.get_model('busqueda', 'SugerenciaSemantica')
    SugerenciaSemantica.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0003_sugerenciasemantica_busquedasemantica_envioembedding_and_more'),
    ]

    operations = [
        migrations.RunPython(cargar_sugerencias_iniciales, eliminar_sugerencias),
    ]
