# Generated by Django 5.2.4 on 2025-11-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0004_cargar_sugerencias_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='busquedasemantica',
            name='costo_consulta',
            field=models.DecimalField(decimal_places=8, default=0.0, help_text='Costo en USD de la consulta según tokens utilizados', max_digits=10, verbose_name='Costo de la Consulta (USD)'),
        ),
        migrations.AddField(
            model_name='busquedasemantica',
            name='modelo_utilizado',
            field=models.CharField(default='text-embedding-3-small', max_length=100, verbose_name='Modelo de Embedding Utilizado'),
        ),
        migrations.AddField(
            model_name='busquedasemantica',
            name='tokens_utilizados',
            field=models.PositiveIntegerField(default=0, verbose_name='Tokens Utilizados'),
        ),
    ]
