# Generated by Django 5.2.4 on 2025-11-21 20:58

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0007_actualizar_embedding_pgvector'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='envioembedding',
            new_name='busqueda_en_modelo__08fb29_idx',
            old_name='busqueda_en_modelo__81e0a9_idx',
        ),
        migrations.RenameIndex(
            model_name='envioembedding',
            new_name='busqueda_en_fecha_g_2727ab_idx',
            old_name='busqueda_en_fecha_g_6f5e42_idx',
        ),
        migrations.RemoveField(
            model_name='envioembedding',
            name='embedding_vector_new',
        ),
        migrations.AlterField(
            model_name='envioembedding',
            name='embedding_vector',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, help_text='Vector de embedding nativo de pgvector', null=True, verbose_name='Vector de Embedding'),
        ),
    ]
