# Generated by Django 5.2.4 on 2025-11-26 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0009_refactorizar_tablas_busqueda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Renombrar índice embedding_b_usuario_idx solo si existe, sino crear el nuevo directamente
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    -- Si el índice viejo existe, renombrarlo
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = 'embedding_b_usuario_idx'
                    ) THEN
                        ALTER INDEX embedding_b_usuario_idx RENAME TO embedding_b_usuario_275ca3_idx;
                    -- Si no existe, crear el nuevo índice si la tabla existe
                    ELSIF EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'embedding_busqueda'
                    ) AND NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = 'embedding_b_usuario_275ca3_idx'
                    ) THEN
                        CREATE INDEX embedding_b_usuario_275ca3_idx 
                        ON embedding_busqueda (usuario_id, fecha_busqueda DESC);
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = 'embedding_b_usuario_275ca3_idx'
                    ) THEN
                        ALTER INDEX embedding_b_usuario_275ca3_idx RENAME TO embedding_b_usuario_idx;
                    END IF;
                END $$;
            """
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='embeddingbusqueda',
                    new_name='embedding_b_usuario_275ca3_idx',
                    old_name='embedding_b_usuario_idx',
                ),
            ]
        ),
        # Renombrar índices de envioembedding
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    -- Renombrar busqueda_en_modelo__08fb29_idx
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = 'busqueda_en_modelo__08fb29_idx'
                    ) THEN
                        ALTER INDEX busqueda_en_modelo__08fb29_idx RENAME TO embedding_e_modelo__55dfe1_idx;
                    ELSIF EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'embedding_envio' OR table_name = 'busqueda_envioembedding'
                    ) AND NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = 'embedding_e_modelo__55dfe1_idx'
                    ) THEN
                        -- Crear índice si la tabla existe pero el índice no
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'embedding_envio') THEN
                            CREATE INDEX embedding_e_modelo__55dfe1_idx ON embedding_envio (modelo_utilizado);
                        ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'busqueda_envioembedding') THEN
                            CREATE INDEX embedding_e_modelo__55dfe1_idx ON busqueda_envioembedding (modelo_utilizado);
                        END IF;
                    END IF;
                    
                    -- Renombrar busqueda_en_fecha_g_2727ab_idx
                    IF EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = 'busqueda_en_fecha_g_2727ab_idx'
                    ) THEN
                        ALTER INDEX busqueda_en_fecha_g_2727ab_idx RENAME TO embedding_e_fecha_g_c60383_idx;
                    ELSIF EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'embedding_envio' OR table_name = 'busqueda_envioembedding'
                    ) AND NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = 'embedding_e_fecha_g_c60383_idx'
                    ) THEN
                        -- Crear índice si la tabla existe pero el índice no
                        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'embedding_envio') THEN
                            CREATE INDEX embedding_e_fecha_g_c60383_idx ON embedding_envio (fecha_generacion DESC);
                        ELSIF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'busqueda_envioembedding') THEN
                            CREATE INDEX embedding_e_fecha_g_c60383_idx ON busqueda_envioembedding (fecha_generacion DESC);
                        END IF;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'embedding_e_modelo__55dfe1_idx') THEN
                        ALTER INDEX embedding_e_modelo__55dfe1_idx RENAME TO busqueda_en_modelo__08fb29_idx;
                    END IF;
                    IF EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'embedding_e_fecha_g_c60383_idx') THEN
                        ALTER INDEX embedding_e_fecha_g_c60383_idx RENAME TO busqueda_en_fecha_g_2727ab_idx;
                    END IF;
                END $$;
            """
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='envioembedding',
                    new_name='embedding_e_modelo__55dfe1_idx',
                    old_name='busqueda_en_modelo__08fb29_idx',
                ),
                migrations.RenameIndex(
                    model_name='envioembedding',
                    new_name='embedding_e_fecha_g_c60383_idx',
                    old_name='busqueda_en_fecha_g_2727ab_idx',
                ),
            ]
        ),
        # Agregar índice para modelo_utilizado si no existe
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'embedding_busqueda'
                    ) AND NOT EXISTS (
                        SELECT 1 FROM pg_indexes 
                        WHERE indexname = 'embedding_b_modelo__ff4ec0_idx'
                    ) THEN
                        CREATE INDEX embedding_b_modelo__ff4ec0_idx 
                        ON embedding_busqueda (modelo_utilizado);
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS embedding_b_modelo__ff4ec0_idx;
            """
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name='embeddingbusqueda',
                    index=models.Index(fields=['modelo_utilizado'], name='embedding_b_modelo__ff4ec0_idx'),
                ),
            ]
        ),
        # Renombrar tabla solo si existe con el nombre viejo
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    -- Si existe busqueda_envioembedding, renombrarla a embedding_envio
                    IF EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'busqueda_envioembedding'
                    ) AND NOT EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'embedding_envio'
                    ) THEN
                        ALTER TABLE busqueda_envioembedding RENAME TO embedding_envio;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.tables 
                        WHERE table_name = 'embedding_envio'
                    ) THEN
                        ALTER TABLE embedding_envio RENAME TO busqueda_envioembedding;
                    END IF;
                END $$;
            """
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='envioembedding',
                    table='embedding_envio',
                ),
            ]
        ),
    ]
